### ISSUE TITLE
Having a stack with id = `*` results in `ERROR: no compatible stacks among provided buildpacks`

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/git#109]
## What happened?
Trying to `pack build` with this buildpack, v0.4.0

Try to run integration tests here: https://github.com/paketo-buildpacks/go/pull/558/commits/09aa607690e4cbb62dcf8756c4a7bc5913c90ac6

## What was the actual behavior?
results in `ERROR: no compatible stacks among provided buildpacks`

## Thoughts
Could be related to the `stacks` change here: https://github.com/paketo-buildpacks/git/compare/v0.3.0...v0.4.0#diff-5f54cb49d0e28117084fad482c0daf89502d4ecb329230071fcf78e56dc939b3

This seems like a bigger issue?

**Comment by ryanmoran** [comment]
This seems like a bug in `pack builder create` since `*` is an allowed wildcard stack ID: https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpack-implementations.

**Comment by samj1912** [comment]
Is this observable in the latest pack version? (0.24)
